logging:
  level:
    root: WARN
    org:
      springframework:
        security: DEBUG
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  output:
    ansi:
      enabled: always
  profiles:
    default: development